### ISSUE TITLE
Deploying contract to private network

### ISSUE THREAD

**Issue by frods** [ethereum/aleth#5294]
I have set up a private network and am able to send transactions between accounts. I am now trying to deploy a smart contract to the network and interact with it.

My setup is:
aleth 1.4.0rc7
solc 0.4.25
ethereum-console 1.0.4

I'm compiling and deploying the following contract https://github.com/frods/ERC20Token

With the following steps:
Compile
```
solc --combined-json abi,bin,interface ERC20Coin.sol > ERC20Coin.json
```

Deploy (in ethereum-console connected to running aleth node)
```
var contractSource = JSON.parse(fs.readFileSync('../ERC20Token/contracts/ERC20Coin.json', 'utf8'))
var contract = new eth.Contract(JSON.parse(contractSource.contracts['ERC20Coin.sol:ERC20Coin'].abi))
contractInstance.deploy(({data: contract.contracts['ERC20Coin.sol:ERC20Coin'].bin, arguments: ["MyCoin", "MC", 18, 100000000000]}).send({from: "00195f4b51509e358eadf8e5bd568a5240e8805f", gas: 250000})
```
The transaction is mined and I get a transaction receipt like
```
> eth.getTransactionReceipt("0xc01661bc7027827c8965a11a60d95df4f57ca7ea011d2683d42d7966179c7628")
{ blockHash:
   '0xe0f2396155c7d10f0bd0629aef336eb60a9d7d4c2c0796f76fc10c28a32bc360',
  blockNumber: 1595,
  contractAddress: '0xC06B80Cdba12Cd0FaD94Fd697bdD38ad93C28918',
  cumulativeGasUsed: 250000,
  gasUsed: 250000,
  logs: [],
  logsBloom:
   '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  status: '0',
  transactionHash:
   '0xc01661bc7027827c8965a11a60d95df4f57ca7ea011d2683d42d7966179c7628',
  transactionIndex: 0 }
```

Then I try to interact with the contract
```
var contractInstance = new eth.Contract(JSON.parse(contractSource.contracts['ERC20Coin.sol:ERC20Coin'].abi), "0xC06B80Cdba12Cd0FaD94Fd697bdD38ad93C28918")
contractInstance.name().call()
contractInstance.balanceOf("00195f4b51509e358eadf8e5bd568a5240e8805f").call()
```

And get errors like

```
Error: ERROR: The returned value is not a convertible string:
    at SolidityTypeString.formatOutputString [as _outputFormatter] (/Users/frods/Work/ethereumconsole/node_modules/web3-eth-abi/src/formatters.js:249:15)
    at /Users/frods/Work/ethereumconsole/node_modules/web3-eth-abi/src/type.js:246:25
    at SolidityTypeString.SolidityType.decode (/Users/frods/Work/ethereumconsole/node_modules/web3-eth-abi/src/type.js:247:11)
    at /Users/frods/Work/ethereumconsole/node_modules/web3-eth-abi/src/index.js:327:49
    at Array.forEach (<anonymous>)
    at ABICoder.decodeParameters (/Users/frods/Work/ethereumconsole/node_modules/web3-eth-abi/src/index.js:326:13)
    at Contract._decodeMethodReturn (/Users/frods/Work/ethereumconsole/node_modules/web3-eth-contract/src/index.js:459:22)
    at Method.outputFormatter (/Users/frods/Work/ethereumconsole/node_modules/web3-eth-contract/src/index.js:812:46)
    at Method.formatOutput (/Users/frods/Work/ethereumconsole/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (/Users/frods/Work/ethereumconsole/node_modules/web3-core-method/src/index.js:467:33)
    at Object.<anonymous> (/Users/frods/Work/ethereumconsole/node_modules/web3-core-requestmanager/src/index.js:147:9)
    at callback (/Users/frods/Work/ethereumconsole/node_modules/web3-providers-ipc/src/index.js:65:40)
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/Users/frods/Work/ethereumconsole/node_modules/web3-providers-ipc/src/index.js:76:51)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

```
Error: Couldn't decode uint256 from ABI: 0x
    at SolidityTypeUInt.formatOutputUInt [as _outputFormatter] (/Users/frods/Work/ethereumconsole/node_modules/web3-eth-abi/src/formatters.js:174:15)
    at SolidityTypeUInt.SolidityType.decode (/Users/frods/Work/ethereumconsole/node_modules/web3-eth-abi/src/type.js:252:17)
    at /Users/frods/Work/ethereumconsole/node_modules/web3-eth-abi/src/index.js:327:49
    at Array.forEach (<anonymous>)
    at ABICoder.decodeParameters (/Users/frods/Work/ethereumconsole/node_modules/web3-eth-abi/src/index.js:326:13)
    at Contract._decodeMethodReturn (/Users/frods/Work/ethereumconsole/node_modules/web3-eth-contract/src/index.js:459:22)
    at Method.outputFormatter (/Users/frods/Work/ethereumconsole/node_modules/web3-eth-contract/src/index.js:812:46)
    at Method.formatOutput (/Users/frods/Work/ethereumconsole/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (/Users/frods/Work/ethereumconsole/node_modules/web3-core-method/src/index.js:467:33)
    at Object.<anonymous> (/Users/frods/Work/ethereumconsole/node_modules/web3-core-requestmanager/src/index.js:147:9)
    at callback (/Users/frods/Work/ethereumconsole/node_modules/web3-providers-ipc/src/index.js:65:40)
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/Users/frods/Work/ethereumconsole/node_modules/web3-providers-ipc/src/index.js:76:51)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

From looking up the errors everything suggests an incompatibility between the abi versions of the contract and the runtime. If that is the reason then how do I check the version of Solidity used by aleth and ethereum-console?

I may be doing something totally wrong or stupid. If that is the case I would appreciate being pointed in the right direction.

**Comment by gumb0** [comment]
Could it run out of gas? (try increasing gas in deploy transaction)

I can suggest enabling verbose log in aleth (`-v 4`) and looking for errors there when tx is executed.

**Comment by frods** [comment]
The gas was the issue. I was able to create the contract and interact with it!

I also had to increase the gasLimit of the genesis block. Is the current live network the mainNetwork or Ropsten? I see Ropsten has a much higher gas limit than mainNetwork in the genesis configuration.
