### ISSUE TITLE
Aleth core dump

### ISSUE THREAD

**Issue by Yangwa** [ethereum/aleth#5673]
#0  0x000055bb8de22e16 in dev::eth::EthereumPeer::requestBlockHeaders (this=this@entry=0x7fce706f68e0, _startHash=..., _count=_count@entry=1, _skip=_skip@entry=0, _reverse=_reverse@entry=false)
    at /home/teddy/project/aleth_constantinople/constantinople/libethereum/EthereumPeer.cpp:122
#1  0x000055bb8de93661 in dev::eth::BlockChainSync::syncPeer (this=0x55bb8fee9f60, _peerID=..., _force=_force@entry=false) at /home/teddy/project/aleth_constantinople/constantinople/libethereum/BlockChainSync.cpp:274
#2  0x000055bb8de93d7e in dev::eth::BlockChainSync::<lambda(const NodeID&)>::operator() (_peerID=..., __closure=<optimized out>) at /home/teddy/project/aleth_constantinople/constantinople/libethereum/BlockChainSync.cpp:289
#3  std::_Function_handler<bool(const dev::FixedHash<64>&), dev::eth::BlockChainSync::continueSync()::<lambda(const NodeID&)> >::_M_invoke(const std::_Any_data &, const dev::FixedHash<64> &) (__functor=..., __args#0=...)
    at /usr/include/c++/7/bits/std_function.h:302
#4  0x000055bb8e0ab52b in std::function<bool (dev::FixedHash<64u> const&)>::operator()(dev::FixedHash<64u> const&) const (__args#0=..., this=0x7fcf4500e4d0) at /usr/include/c++/7/bits/std_function.h:706
#5  dev::p2p::Host::forEachPeer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<bool (dev::FixedHash<64u> const&)>) const (this=this@entry=0x7ffed8554500, _capabilityName="eth", _f=...)
    at /home/teddy/project/aleth_constantinople/constantinople/libp2p/Host.cpp:1040
#6  0x000055bb8e0f3149 in dev::p2p::(anonymous namespace)::CapabilityHost::foreachPeer(const std::__cxx11::string &, std::function<bool(const dev::FixedHash<64>&)>) const (this=<optimized out>, _capabilityName="eth", _f=...)
    at /home/teddy/project/aleth_constantinople/constantinople/libp2p/CapabilityHost.cpp:109
#7  0x000055bb8de8fe8d in dev::eth::BlockChainSync::continueSync (this=this@entry=0x55bb8fee9f60) at /home/teddy/project/aleth_constantinople/constantinople/libethereum/BlockChainSync.cpp:288
#8  0x000055bb8de909d3 in dev::eth::BlockChainSync::onPeerAborting (this=0x55bb8fee9f60) at /home/teddy/project/aleth_constantinople/constantinople/libethereum/BlockChainSync.cpp:940
#9  0x000055bb8de13867 in (anonymous namespace)::EthereumPeerObserver::onPeerAborting (this=<optimized out>) at /home/teddy/project/aleth_constantinople/constantinople/libethereum/EthereumCapability.cpp:99
#10 0x000055bb8de1416d in dev::eth::EthereumCapability::onDisconnect (this=0x55bb99a09cd0, _peerID=...) at /home/teddy/project/aleth_constantinople/constantinople/libethereum/EthereumCapability.cpp:703
#11 0x000055bb8e0e8f17 in dev::p2p::Session::~Session (this=0x7fceaf12d660, __in_chrg=<optimized out>) at /home/teddy/project/aleth_constantinople/constantinople/libp2p/Session.cpp:60
#12 0x000055bb8dd42806 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7fceaf12d650) at /usr/include/c++/7/bits/shared_ptr_base.h:154
#13 0x000055bb8e0ed9a2 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7fcf4500e808, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:684
#14 std::__shared_ptr<dev::p2p::SessionFace, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7fcf4500e800, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:1123
#15 std::shared_ptr<dev::p2p::SessionFace>::~shared_ptr (this=0x7fcf4500e800, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr.h:93
#16 dev::p2p::Session::<lambda(boost::system::error_code, std::size_t)>::~<lambda> (this=0x7fcf4500e7f8, __in_chrg=<optimized out>) at /home/teddy/project/aleth_constantinople/constantinople/libp2p/Session.cpp:335
#17 boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)> >::~read_op (this=0x7fcf4500e7d0, __in_chrg=<optimized out>) at /home/teddy/.hunter/_Base/c4cfcc0/af6c4e5/ef3c3eb/Install/include/boost/asio/impl/read.hpp:221
#18 boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>::~binder2 (this=0x7fcf4500e7d0, __in_chrg=<optimized out>)
    at /home/teddy/.hunter/_Base/c4cfcc0/af6c4e5/ef3c3eb/Install/include/boost/asio/detail/bind_handler.hpp:108
#19 boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)> > >::do_complete(boost::asio::detail::io_service_impl *, boost::asio::detail::operation *, const boost::system::error_code &, std::size_t) (owner=0x55bb8f7d4be0, base=0x7fcf416c5810) at /home/teddy/.hunter/_Base/c4cfcc0/af6c4e5/ef3c3eb/Install/include/boost/asio/detail/reactive_socket_recv_op.hpp:101
#20 0x000055bb8e0b7c49 in boost::asio::detail::task_io_service_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=..., this=<optimized out>)
    at /home/teddy/.hunter/_Base/c4cfcc0/af6c4e5/ef3c3eb/Install/include/boost/asio/detail/task_io_service_operation.hpp:38
#21 boost::asio::detail::task_io_service::do_run_one (ec=..., this_thread=..., lock=..., this=0x55bb8f7d4be0) at /home/teddy/.hunter/_Base/c4cfcc0/af6c4e5/ef3c3eb/Install/include/boost/asio/detail/impl/task_io_service.ipp:372
#22 boost::asio::detail::task_io_service::run (this=0x55bb8f7d4be0, ec=...) at /home/teddy/.hunter/_Base/c4cfcc0/af6c4e5/ef3c3eb/Install/include/boost/asio/detail/impl/task_io_service.ipp:149
#23 0x000055bb8e0a7db8 in boost::asio::io_service::run (this=0x7ffed8554658) at /home/teddy/.hunter/_Base/c4cfcc0/af6c4e5/ef3c3eb/Install/include/boost/asio/impl/io_service.ipp:59
#24 dev::p2p::Host::doWork (this=0x7ffed8554500) at /home/teddy/project/aleth_constantinople/constantinople/libp2p/Host.cpp:810
#25 0x000055bb8df3b372 in dev::Worker::workLoop (this=0x7ffed8554500) at /home/teddy/project/aleth_constantinople/constantinople/libdevcore/Worker.cpp:140
#26 0x000055bb8df3bc94 in dev::Worker::<lambda()>::operator() (__closure=0x55bb90d8b5c8) at /home/teddy/project/aleth_constantinople/constantinople/libdevcore/Worker.cpp:62
#27 std::__invoke_impl<void, dev::Worker::startWorking()::<lambda()> > (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#28 std::__invoke<dev::Worker::startWorking()::<lambda()> > (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#29 std::thread::_Invoker<std::tuple<dev::Worker::startWorking()::<lambda()> > >::_M_invoke<0> (this=0x55bb90d8b5c8) at /usr/include/c++/7/thread:234
#30 std::thread::_Invoker<std::tuple<dev::Worker::startWorking()::<lambda()> > >::operator() (this=0x55bb90d8b5c8) at /usr/include/c++/7/thread:243
#31 std::thread::_State_impl<std::thread::_Invoker<std::tuple<dev::Worker::startWorking()::<lambda()> > > >::_M_run(void) (this=0x55bb90d8b5c0) at /usr/include/c++/7/thread:186
#32 0x00007fcf873a557f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#33 0x00007fcf876786db in start_thread (arg=0x7fcf4500f700) at pthread_create.c:463
#34 0x00007fcf86a6288f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by moneroexamples** [comment]
Which linux?

**Comment by Yangwa** [comment]
Ubuntu 18.04 LTS

**Comment by Yangwa** [comment]
> Which linux?

Ubuntu 18.04 LTS

**Comment by moneroexamples** [comment]
This issue seems to be related: https://github.com/ethereum/aleth/issues/5633

**Comment by Yangwa** [comment]
> This issue seems to be related: #5633

Thank you. That's exactly the problem
